<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * ChateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChateRepository extends \Doctrine\ORM\EntityRepository
{
}
