<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * CommentairePubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairePubRepository extends \Doctrine\ORM\EntityRepository
{
}
