<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * ContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsRepository extends \Doctrine\ORM\EntityRepository
{
// Depuis un repository 

	public function findByUser( $User)
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb->where('(a.Demandeur = :User OR a.Validateur= :User) AND a.etat=1')
	       ->setParameter('User', $User)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

	public function findByUserInvitation($User){
	  $qb = $this->createQueryBuilder('a');

	  $qb->where('a.Validateur= :User AND a.etat=0')
	       ->setParameter('User', $User)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

	public function checkContact($Demandeur, $Validateur){
	  $qb = $this->createQueryBuilder('a');

	  $qb->where('((a.Validateur= :Demandeur AND a.Demandeur= :Validateur) OR (a.Validateur= :Validateur AND a.Demandeur= :Demandeur)) AND a.etat=1')
	     ->setParameter('Demandeur', $Demandeur)
	     ->setParameter('Validateur', $Validateur)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

}
