<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByEditor( $User)
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb->where('a.utilisateur = :User ')
	       ->setParameter('User', $User)
	  ;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}

}
