<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
	public function UtilisateurOne($id)
{
  $qb = $this->createQueryBuilder('a');

  $qb
    ->where('a.Utilisateur = :id')
    ->setParameter('id', $id)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
}
}
