<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * TDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TDRepository extends \Doctrine\ORM\EntityRepository
{
}
