<?php

namespace NetUniversity\PlatformBundle\Repository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends \Doctrine\ORM\EntityRepository
{
	  public function getLikeQueryBuilder($pattern)
	  {
	    return $this
      ->createQueryBuilder('c')
      ->where('c.utilisateur_id = :pattern')
      ->setParameter('pattern', $pattern)
    ;
	  }
}
